services:
  - type: web
    name: Rails_test
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sample_app-development
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: Rails_test
    databaseName: rails_test_2bqw
    user: rails_test_2bqw_user